### ISSUE TITLE
Not able to find the package formulapi_source

### ISSUE THREAD

**Issue by chrissunny94** [wilselby/formulapi_ROS_simulator#2]
`   Could not find a package configuration file provided by "formulapi_source"
    with any of the following names:

      formulapi_sourceConfig.cmake
      formulapi_source-config.cmake

`

**Comment by wilselby** [comment]
I'm not able to distribute that code since it was purchased through the competition. It's essentially their source code adapted for ROS.

See this section for more details:
https://github.com/wilselby/formulapi_ROS_simulator#formulapi-software-integration
