### ISSUE TITLE
The Gazebo world appears black for me even after updating the absolute file paths

### ISSUE THREAD

**Issue by sisaha9** [wilselby/formulapi_ROS_simulator#3]
I downloaded the package, went to the correct world file and launched it with gazebo but I just get the black track. I made sure to update the <uri> tags to the correct absolute file. What's going wrong?

![Gazebo](https://user-images.githubusercontent.com/49205122/100494926-64bd8a80-30fb-11eb-91c3-11e915e737bd.png)

**Comment by sisaha9** [comment]
The problem seems to be with the DAE file and how it is set to work with Gazebo 2.2. Do we have a more updated DAE file available?

**Comment by wilselby** [comment]
Here's the original [file](https://3dwarehouse.sketchup.com/model/918c85e8-dd05-452b-90c7-86c4885369d3/FormulaPi-Track-1) in Sketchup. You can try downloading it from there and reformatting it.
